M48
; DRILL file {KiCad 7.0.8} date Fri 20 Oct 2023 02:12:03 PM CDT
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-10-20T14:12:03-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0650
%
G90
G05
T1
X4.5217Y-1.626
X6.0886Y-1.626
X6.3031Y-1.626
X7.8701Y-1.626
T0
M30
